name: Build

on: [push]

jobs:
  build-index:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Prepare java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'corretto'
          java-version: '17'  
          
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1435
      
      - name: Build
        run: clj -M resume.clj > index.html
