name: Build

on: [push]

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: install deps
        run: sudo apt-get install -y rlwrap

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1435


      - name: clojure version
        run: clj --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: clj -M resume.clj > docs/index.html

      - name: Deploy onto S3
        uses: hannut91/aws-cli@1.32.49
        with:
          args: s3 cp docs s3://resume.hatemogi.com/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2

      - name: Invalidate CloudFront cache
        uses: hannut91/aws-cli@1.32.49
        with:
          args: cloudfront create-invalidation --no-cli-pager --distribution-id=${{env.CLOUD_FRONT_DISTRIBUTION}} --paths='/*' --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
